# Generated by Django 5.2.5 on 2025-08-25 23:22

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_arabic', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_arabic', models.CharField(blank=True, max_length=200)),
                ('title_french', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('cycle', models.CharField(choices=[('first', 'الدورة الأولى - Premier Cycle'), ('second', 'الدورة الثانية - Deuxième Cycle')], max_length=10)),
                ('order', models.PositiveIntegerField(help_text='Lesson sequence within the cycle')),
                ('objectives', models.TextField(blank=True, help_text='Learning objectives for this lesson')),
                ('prerequisites', models.TextField(blank=True, help_text='What students need to know first')),
                ('difficulty_level', models.CharField(choices=[('easy', 'سهل - Facile'), ('medium', 'متوسط - Moyen'), ('hard', 'صعب - Difficile')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.subject')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['subject', 'grade', 'cycle', 'order'],
                'unique_together': {('subject', 'grade', 'cycle', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'مستند PDF - Document PDF'), ('video', 'فيديو - Vidéo'), ('audio', 'صوت - Audio'), ('image', 'صورة - Image'), ('document', 'مستند - Document Word/Excel'), ('link', 'رابط خارجي - Lien externe'), ('exercise', 'تمرين - Exercice'), ('presentation', 'عرض تقديمي - Présentation')], max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('external_url', models.URLField(blank=True, help_text='YouTube, external resources, etc.')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('is_visible_to_students', models.BooleanField(default=True)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lessons.lesson')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Resource',
                'verbose_name_plural': 'Lesson Resources',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lessontag')),
            ],
            options={
                'unique_together': {('lesson', 'tag')},
            },
        ),
    ]
