# Generated by Django 5.2.5 on 2025-09-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_content'),
        ('schools', '0002_alter_schoolclass_options_alter_schoolclass_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['subject', 'grade', 'track', 'cycle', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.track'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'grade', 'track', 'cycle', 'order')},
        ),
    ]
