# Generated by Django 5.2.5 on 2025-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_options_alter_lesson_unique_together_and_more'),
        ('schools', '0002_alter_schoolclass_options_alter_schoolclass_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['subject', 'grade', 'cycle', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='track',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='schools.Track'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'grade', 'cycle', 'order')},
        ),
    ]
