# Generated by Django 5.2.5 on 2025-10-19 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_many_tracks'),
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Make this lesson visible and accessible to students in this class')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_availability', to='lessons.lesson')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_lesson_availabilities', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_availability', to='schools.schoolclass')),
            ],
            options={
                'verbose_name': 'Lesson Availability',
                'verbose_name_plural': 'Lesson Availabilities',
                'ordering': ['lesson__order', 'school_class__name'],
                'unique_together': {('lesson', 'school_class')},
            },
        ),
    ]
