# Generated by Django 5.2.5 on 2025-12-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown formatted content'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'مستند PDF - Document PDF'), ('video', 'فيديو - Vidéo'), ('audio', 'صوت - Audio'), ('image', 'صورة - Image'), ('document', 'مستند - Document Word/Excel'), ('link', 'رابط خارجي - Lien externe'), ('exercise', 'تمرين - Exercice'), ('presentation', 'عرض تقديمي - Présentation'), ('markdown', 'ماركداون - Markdown')], max_length=20),
        ),
    ]
