# Generated by Django 5.2.5 on 2025-12-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_add_blocks_content'),
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100, verbose_name='Arabic Name')),
                ('fr_name', models.CharField(max_length=100, verbose_name='French Name')),
                ('en_name', models.CharField(max_length=100, verbose_name='English Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='schools.subject')),
            ],
            options={
                'verbose_name': 'Subject Category',
                'verbose_name_plural': 'Subject Categories',
                'ordering': ['subject', 'ar_name'],
            },
        ),
    ]
