# Generated by Django 5.2.5 on 2025-12-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_subjectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.subjectcategory'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
