# Generated by Django 5.2.5 on 2025-11-26 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('MESSAGE_SENT', 'Message sent'), ('HOMEWORK_CREATED', 'Homework created'), ('HOMEWORK_PUBLISHED', 'Homework published'), ('PAYMENT_RECORDED', 'Payment recorded'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('SYSTEM', 'System'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_app', models.CharField(blank=True, max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_14fffc_idx'), models.Index(fields=['action'], name='activity_lo_action_794c49_idx'), models.Index(fields=['actor'], name='activity_lo_actor_i_608160_idx')],
            },
        ),
    ]
