# Generated by Django 5.2.5 on 2025-08-21 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Format: YYYY-YYYY', max_length=9, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRESCHOOL', 'Préscolaire'), ('PRIMARY', 'Primaire'), ('LOWER_SECONDARY', 'Collège'), ('UPPER_SECONDARY', 'Lycée')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(blank=True, max_length=100)),
                ('name_french', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Order of progression (e.g., 1 for Preschool, 2 for Primary)', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="e.g., 'B101'", max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('GYM', 'Gymnasium'), ('COMPUTER', 'Computer Lab'), ('ART', 'Art Room'), ('MUSIC', 'Music Room'), ('OTHER', 'Other')], default='CLASSROOM', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(blank=True, max_length=100)),
                ('name_french', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(help_text="e.g., 'MATH101'", max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.PositiveIntegerField(help_text='Numeric value of the grade within the level (e.g., 1, 2, 3)')),
                ('name', models.CharField(help_text="e.g., '1ère Année Primaire'", max_length=100)),
                ('name_arabic', models.CharField(blank=True, max_length=100)),
                ('name_french', models.CharField(blank=True, max_length=100)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.educationallevel')),
            ],
            options={
                'ordering': ['educational_level__order', 'grade_number'],
                'unique_together': {('educational_level', 'grade_number')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_arabic', models.CharField(blank=True, max_length=200)),
                ('name_french', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_set', to='schools.academicyear')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_school', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text="e.g., 'A', 'B', 'Science-1'", max_length=10)),
                ('name', models.CharField(editable=False, max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='schools.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.grade')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['grade__educational_level__order', 'grade__grade_number', 'section'],
                'unique_together': {('grade', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('weekly_hours', models.PositiveIntegerField(default=2)),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='schools.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configs', to='schools.subject')),
            ],
            options={
                'unique_together': {('subject', 'grade')},
            },
        ),
    ]
