# Generated by Django 5.2.5 on 2025-09-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['grade__educational_level__order', 'grade__grade_number', 'track__order', 'section'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(help_text="e.g., 'A', 'B', 'Groupe 1'", max_length=10),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Sciences Mathématiques A'", max_length=150)),
                ('name_arabic', models.CharField(blank=True, help_text="e.g., 'علوم رياضية أ'", max_length=150)),
                ('name_french', models.CharField(blank=True, help_text="e.g., 'Sciences Mathématiques A'", max_length=150)),
                ('code', models.CharField(help_text="e.g., 'SMA', 'SPB'", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the track')),
                ('description_arabic', models.TextField(blank=True)),
                ('description_french', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order within the grade')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='schools.grade')),
            ],
            options={
                'ordering': ['grade__educational_level__order', 'grade__grade_number', 'order', 'name'],
                'unique_together': {('grade', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Optional track/path for specialized programs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.track'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('grade', 'track', 'section', 'academic_year')},
        ),
    ]
