# Generated by Django 5.2.5 on 2025-09-25 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schoolclass_options_alter_schoolclass_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers assigned to this class', limit_choices_to={'role': 'TEACHER'}, related_name='teaching_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
