# Generated by Django 5.2.5 on 2025-09-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_teachers_to_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(blank=True, help_text="e.g., 'G1', 'G7', '1BAC'", max_length=20, null=True, unique=True),
        ),
    ]
