# Generated by Django 5.2.5 on 2025-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_facebook_url_school_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='fix_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='pattent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='rc_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
