# Generated by Django 5.2.5 on 2025-10-16 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_fix_phone_school_pattent_school_rc_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Friendly name or route identifier for the vehicle', max_length=120)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibus'), ('VAN', 'Van'), ('CAR', 'Car'), ('OTHER', 'Other')], default='BUS', max_length=20)),
                ('model', models.CharField(help_text='Manufacturer and model, e.g., Mercedes Sprinter', max_length=120)),
                ('plate_number', models.CharField(max_length=25, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of passengers', null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_oil_change_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Owning school, optional for single-school deployments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='schools.school')),
            ],
            options={
                'ordering': ['vehicle_type', 'model', 'plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(help_text='Type of service or repair performed', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('service_location', models.CharField(blank=True, help_text='Where the service was carried out', max_length=255)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Vehicle mileage at the time of service', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='schools.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
