# Generated by Django 5.2.5 on 2026-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasoilrecord',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('VOUCHER', 'Voucher (Bone)')], default='CASH', max_length=10),
        ),
    ]
