# Generated by Django and manually edited

from django.db import migrations, models
import django.db.models.deletion
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_options_alter_lesson_unique_together_and_more'),
        ('schools', '0002_alter_schoolclass_options_alter_schoolclass_name_and_more'),
        ('homework', '0002_question_author_question_grade_question_subject_and_more'),
    ]

    operations = [
        # Rename Assignment table to Homework
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Homework',
        ),

        # Rename AssignmentReward table to HomeworkReward
        migrations.RenameModel(
            old_name='AssignmentReward',
            new_name='HomeworkReward',
        ),

        # Update field names in related models
        migrations.RenameField(
            model_name='bookexercise',
            old_name='assignment',
            new_name='homework',
        ),

        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='homework',
        ),

        migrations.RenameField(
            model_name='question',
            old_name='assignment',
            new_name='homework',
        ),

        migrations.RenameField(
            model_name='rewardtransaction',
            old_name='assignment',
            new_name='homework',
        ),

        migrations.RenameField(
            model_name='studentbadge',
            old_name='assignment',
            new_name='homework',
        ),

        # Update field names in Homework model
        migrations.RenameField(
            model_name='homework',
            old_name='assignment_format',
            new_name='homework_format',
        ),

        migrations.RenameField(
            model_name='homework',
            old_name='assignment_type',
            new_name='homework_type',
        ),

        # Update foreign key references in HomeworkReward
        migrations.RenameField(
            model_name='homeworkreward',
            old_name='assignment',
            new_name='homework',
        ),

        # Update foreign key references in Submission Meta
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('homework', 'student', 'attempt_number')},
        ),

        # Add Exercise model
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_arabic', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('exercise_format', models.CharField(choices=[('mixed', 'مختلط - Format mixte'), ('qcm_only', 'أسئلة اختيار متعدد - QCM uniquement'), ('open_only', 'أسئلة مفتوحة - Questions ouvertes'), ('practical', 'تطبيقي - Travaux pratiques'), ('interactive', 'تفاعلي - Interactif')], default='mixed', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ - Débutant'), ('intermediate', 'متوسط - Intermédiaire'), ('advanced', 'متقدم - Avancé'), ('expert', 'خبير - Expert')], default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within lesson')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated minutes to complete', null=True)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Optional time limit in minutes', null=True)),
                ('is_timed', models.BooleanField(default=False)),
                ('total_points', models.DecimalField(decimal_places=2, default=10.00, max_digits=5)),
                ('auto_grade', models.BooleanField(default=True, help_text='Auto-grade when possible')),
                ('randomize_questions', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('allow_multiple_attempts', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts')),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to='users.user')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
                ('prerequisite_exercises', models.ManyToManyField(blank=True, related_name='unlocks_exercises', to='homework.exercise')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['lesson', 'order', 'created_at'],
            },
        ),

        # Add ExerciseReward model
        migrations.CreateModel(
            name='ExerciseReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_points', models.PositiveIntegerField(default=2, help_text='Points for starting exercise')),
                ('completion_points', models.PositiveIntegerField(default=5, help_text='Points for completing exercise')),
                ('completion_coins', models.PositiveIntegerField(default=1)),
                ('perfect_score_bonus', models.PositiveIntegerField(default=10, help_text='100% score bonus')),
                ('high_score_bonus', models.PositiveIntegerField(default=5, help_text='>=80% score bonus')),
                ('improvement_bonus', models.PositiveIntegerField(default=3, help_text='Score improvement bonus')),
                ('daily_streak_bonus', models.PositiveIntegerField(default=2, help_text='Bonus for daily exercise completion')),
                ('lesson_completion_bonus', models.PositiveIntegerField(default=15, help_text='Bonus for completing all lesson exercises')),
                ('difficulty_multiplier', models.DecimalField(decimal_places=2, default=1.00, max_digits=3)),
                ('first_attempt_multiplier', models.DecimalField(decimal_places=2, default=1.50, max_digits=3)),
                ('base_xp', models.PositiveIntegerField(default=5)),
                ('bonus_xp', models.PositiveIntegerField(default=10, help_text='XP for excellent performance')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_config', to='homework.exercise')),
            ],
        ),

        # Add exercise field to Question model
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='homework.exercise'),
        ),

        # Add ExerciseSubmission model
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'بدء - Commencé'), ('in_progress', 'قيد التقدم - En cours'), ('completed', 'مكتمل - Complété'), ('auto_graded', 'مُصحح تلقائياً - Auto-corrigé'), ('reviewed', 'مراجع - Révisé')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Minutes taken', null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('is_best_score', models.BooleanField(default=True, help_text="Is this the student's best attempt?")),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('previous_best_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('rewards_calculated', models.BooleanField(default=False)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('improvement_from_last', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auto_feedback', models.TextField(blank=True, help_text='Generated feedback based on performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to='homework.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to='users.user')),
            ],
            options={
                'verbose_name': 'Exercise Submission',
                'verbose_name_plural': 'Exercise Submissions',
                'ordering': ['-created_at'],
                'unique_together': {('exercise', 'student', 'attempt_number')},
            },
        ),

        # Add ExerciseAnswer model
        migrations.CreateModel(
            name='ExerciseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_partial_credit', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(blank=True, help_text='Seconds spent on this question', null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('is_final_answer', models.BooleanField(default=True)),
                ('hint_used', models.BooleanField(default=False)),
                ('help_requested', models.BooleanField(default=False)),
                ('exercise_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_answers', to='homework.exercisesubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='homework.questionchoice')),
            ],
            options={
                'ordering': ['question__order', 'attempt_count'],
                'unique_together': {('exercise_submission', 'question', 'attempt_count')},
            },
        ),

        # Add ExerciseAnswerFile model
        migrations.CreateModel(
            name='ExerciseAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file', folder='exercise_answer_files/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.exerciseanswer')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),

        # Add exercise and exercise_submission fields to RewardTransaction
        migrations.AddField(
            model_name='rewardtransaction',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.exercise'),
        ),

        migrations.AddField(
            model_name='rewardtransaction',
            name='exercise_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.exercisesubmission'),
        ),

        # Add exercise and exercise_submission fields to StudentBadge
        migrations.AddField(
            model_name='studentbadge',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.exercise'),
        ),

        migrations.AddField(
            model_name='studentbadge',
            name='exercise_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.exercisesubmission'),
        ),
    ]