# Generated by Django 5.2.5 on 2025-10-10 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_rename_assignment_to_homework_and_add_exercises'),
        ('schools', '0004_grade_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schools.grade'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schools.schoolclass'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schools.subject'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FillBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Blank position (1-based)')),
                ('label', models.CharField(blank=True, help_text='Optional label like B1, B2', max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='homework.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='homework.fillblank')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=300)),
                ('right_text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for authoring')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='homework.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('correct_position', models.PositiveIntegerField(help_text='Correct order position (1-based)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='homework.question')),
            ],
            options={
                'ordering': ['correct_position'],
            },
        ),
        migrations.CreateModel(
            name='AnswerFillBlankSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_selections', to='homework.questionanswer')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.fillblank')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.fillblankoption')),
            ],
            options={
                'unique_together': {('question_answer', 'blank')},
            },
        ),
        migrations.CreateModel(
            name='AnswerMatchingSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_selections', to='homework.questionanswer')),
                ('left_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_left', to='homework.matchingpair')),
                ('selected_right_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_selected_right', to='homework.matchingpair')),
            ],
            options={
                'unique_together': {('question_answer', 'left_pair')},
            },
        ),
        migrations.CreateModel(
            name='AnswerOrderingSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_position', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_selections', to='homework.questionanswer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.orderingitem')),
            ],
            options={
                'unique_together': {('question_answer', 'item')},
            },
        ),
    ]
