# Generated by Django 5.2.5 on 2025-10-19 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_homework_grade_alter_homework_school_class_and_more'),
        ('lessons', '0005_lessonavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ - Non commencé'), ('in_progress', 'قيد التقدم - En cours'), ('completed', 'مكتمل - Complété')], default='not_started', max_length=20)),
                ('exercises_completed', models.PositiveIntegerField(default=0, help_text='Number of exercises completed')),
                ('exercises_total', models.PositiveIntegerField(default=0, help_text='Total exercises in this lesson')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of exercises completed', max_digits=5)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average score across all completed exercises', max_digits=5, null=True)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total points earned from all exercises', max_digits=8)),
                ('total_points_possible', models.DecimalField(decimal_places=2, default=0.0, help_text='Total possible points from completed exercises', max_digits=8)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_questions_correct', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of correct answers', max_digits=5)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in minutes')),
                ('first_viewed_at', models.DateTimeField(blank=True, help_text='When student first viewed the lesson page', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When student started first exercise', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When student completed all exercises', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lessons.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress Records',
                'ordering': ['-last_accessed', '-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='homework_le_student_3d192f_idx'), models.Index(fields=['lesson', 'status'], name='homework_le_lesson__431219_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
