# Generated by Django 5.2.5 on 2025-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexercise',
            name='book_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookexercise',
            name='book_title_arabic',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookexercise',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fillblankoption',
            name='option_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='left_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orderingitem',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
