# Generated by Django 5.2.5 on 2025-11-23 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20, null=True)),
                ('homework_completed', models.BooleanField(default=False)),
                ('behavior_score', models.IntegerField(blank=True, help_text='Optional teacher input (1-10)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Daily Summaries',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentTermPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TRIMESTER_1', 'Trimester 1'), ('TRIMESTER_2', 'Trimester 2'), ('TRIMESTER_3', 'Trimester 3'), ('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2')], max_length=20)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Rank in class for this subject', null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_performances', to='schools.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_performances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='schools.subject')),
            ],
            options={
                'ordering': ['student', 'academic_year', 'term', 'subject'],
                'unique_together': {('student', 'academic_year', 'term', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start date of the week (usually Monday)')),
                ('classes_taught', models.PositiveIntegerField(default=0)),
                ('homeworks_assigned', models.PositiveIntegerField(default=0)),
                ('parent_communications', models.PositiveIntegerField(default=0, help_text='Count from Communication App')),
                ('average_student_attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('teacher', 'week_start')},
            },
        ),
    ]
