# Generated by Django 5.2.5 on 2026-01-05 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of completed tasks', max_digits=5)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average star rating across all rated tasks', max_digits=3, null=True)),
                ('total_rated_tasks', models.PositiveIntegerField(default=0)),
                ('five_star_count', models.PositiveIntegerField(default=0)),
                ('four_star_count', models.PositiveIntegerField(default=0)),
                ('three_star_count', models.PositiveIntegerField(default=0)),
                ('two_star_count', models.PositiveIntegerField(default=0)),
                ('one_star_count', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.DurationField(blank=True, help_text='Average time to complete tasks', null=True)),
                ('on_time_completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of tasks completed before due date', max_digits=5)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive days with completed tasks')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_task_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Task Progress',
                'verbose_name_plural': 'User Task Progress',
                'db_table': 'tasks_usertaskprogress',
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_arabic', models.CharField(blank=True, max_length=200)),
                ('title_french', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_arabic', models.TextField(blank=True)),
                ('description_french', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار - En attente'), ('IN_PROGRESS', 'قيد التنفيذ - En cours'), ('DONE', 'تم الإنجاز - Terminé'), ('COMPLETE', 'مكتمل - Complété')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة - Basse'), ('MEDIUM', 'متوسطة - Moyenne'), ('HIGH', 'عالية - Haute'), ('URGENT', 'عاجلة - Urgente')], default='MEDIUM', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Admin rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_feedback', models.TextField(blank=True)),
                ('user_notes', models.TextField(blank=True, help_text='Notes from assignee')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'TEACHER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'db_table': 'tasks_dailytask',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='tasks_daily_assigne_9d280f_idx'), models.Index(fields=['assigned_by', 'created_at'], name='tasks_daily_assigne_347fd0_idx'), models.Index(fields=['status', 'due_date'], name='tasks_daily_status_5c2932_idx')],
            },
        ),
    ]
