# Generated by Django 5.2.5 on 2026-01-02 17:31

from django.db import migrations


def migrate_payment_transactions(apps, schema_editor):
    """
    Create FinancialTransaction records for all existing Payment records.
    """
    Payment = apps.get_model('finance', 'Payment')
    FinancialTransaction = apps.get_model('finance', 'FinancialTransaction')

    payment_count = 0
    for payment in Payment.objects.all():
        # Check if transaction already exists (idempotent)
        if not FinancialTransaction.objects.filter(invoice=payment.invoice, amount=payment.amount, transaction_date=payment.date).exists():
            FinancialTransaction.objects.create(
                transaction_type='INCOME',
                income_category='STUDENT_FEES',
                amount=payment.amount,
                transaction_date=payment.date,
                academic_year=payment.invoice.academic_year,
                invoice=payment.invoice,
                description=f"Student fee payment - Invoice #{payment.invoice.id}",
                payment_method=payment.method,
                reference_number=payment.transaction_id or '',
                status='COMPLETED',
                recorded_by=payment.recorded_by,
                notes=payment.notes
            )
            payment_count += 1

    print(f"Created {payment_count} FinancialTransaction records from existing Payment records")


def migrate_gasoil_transactions(apps, schema_editor):
    """
    Create FinancialTransaction records for all existing GasoilRecord records.
    """
    try:
        GasoilRecord = apps.get_model('schools', 'GasoilRecord')
        FinancialTransaction = apps.get_model('finance', 'FinancialTransaction')
        AcademicYear = apps.get_model('schools', 'AcademicYear')
    except LookupError:
        # If GasoilRecord model doesn't exist yet, skip this migration
        print("GasoilRecord model not found, skipping gasoil transaction migration")
        return

    gasoil_count = 0
    for record in GasoilRecord.objects.all():
        # Check if transaction already exists (idempotent)
        if not FinancialTransaction.objects.filter(gasoil_record=record).exists():
            # Try to find the academic year that contains this fuel record date
            academic_year = AcademicYear.objects.filter(
                start_date__lte=record.refuel_date,
                end_date__gte=record.refuel_date
            ).first()

            # Fallback to current academic year if no match
            if not academic_year:
                academic_year = AcademicYear.objects.filter(is_current=True).first()

            # Only create transaction if we have an academic year
            if academic_year:
                description = f"Fuel refill for {record.vehicle} - {record.liters}L"
                if hasattr(record, 'fuel_station') and record.fuel_station:
                    description += f" at {record.fuel_station}"

                FinancialTransaction.objects.create(
                    transaction_type='EXPENSE',
                    expense_category='FUEL',
                    amount=record.amount,
                    transaction_date=record.refuel_date,
                    academic_year=academic_year,
                    gasoil_record=record,
                    description=description,
                    payment_method='CASH',
                    reference_number=record.receipt_number or '',
                    status='COMPLETED',
                    notes=record.notes or ''
                )
                gasoil_count += 1

    print(f"Created {gasoil_count} FinancialTransaction records from existing GasoilRecord records")


def reverse_migration(apps, schema_editor):
    """
    Remove FinancialTransaction records created by this migration.
    """
    FinancialTransaction = apps.get_model('finance', 'FinancialTransaction')

    # Delete transactions linked to invoices (from payments)
    deleted_payment_transactions = FinancialTransaction.objects.filter(
        invoice__isnull=False,
        income_category='STUDENT_FEES'
    ).delete()

    # Delete transactions linked to gasoil records
    deleted_gasoil_transactions = FinancialTransaction.objects.filter(
        gasoil_record__isnull=False,
        expense_category='FUEL'
    ).delete()

    print(f"Deleted {deleted_payment_transactions[0]} payment transactions and {deleted_gasoil_transactions[0]} gasoil transactions")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budgetcategory_employmentcontract_expenserecord_and_more'),
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),  # Pinned to specific migration to avoid inconsistent history
    ]

    operations = [
        migrations.RunPython(migrate_payment_transactions, reverse_migration),
        migrations.RunPython(migrate_gasoil_transactions, reverse_migration),
    ]
