# Generated by Django 5.2.5 on 2025-08-27 11:20

import cloudinary.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when attendance was taken')),
                ('status', models.CharField(choices=[('not_started', 'لم تبدأ - Not Started'), ('in_progress', 'جارية - In Progress'), ('completed', 'مكتملة - Completed'), ('cancelled', 'ملغية - Cancelled')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='General session notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='taken_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر - Present'), ('absent', 'غائب - Absent'), ('late', 'متأخر - Late'), ('excused', 'غياب مبرر - Excused Absence')], default='present', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.TimeField(blank=True, help_text='Actual arrival time for late students', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teacher notes for this student')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('attendance_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SchoolTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.schoolclass')),
            ],
            options={
                'verbose_name': 'School Timetable',
                'verbose_name_plural': 'School Timetables',
                'ordering': ['school_class__grade__educational_level__order', 'school_class__grade__grade_number', 'school_class__section'],
                'unique_together': {('school_class', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentAbsenceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('clearance_reason', models.CharField(blank=True, choices=[('medical', 'شهادة طبية - Medical Certificate'), ('family', 'حالة طارئة عائلية - Family Emergency'), ('parent_permission', 'إذن من الولي - Parent Permission'), ('school_activity', 'نشاط مدرسي - School Activity'), ('other', 'أخرى - Other (see notes)')], max_length=20, null=True)),
                ('clearance_notes', models.TextField(blank=True)),
                ('clearance_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.attendancerecord')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_flags', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Absence Flag',
                'verbose_name_plural': 'Student Absence Flags',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'attendance_record')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('absence', 'إخطار غياب - Absence Alert'), ('late', 'إخطار تأخير - Late Alert'), ('flag_created', 'علامة غياب - Flag Created'), ('flag_cleared', 'تم حل العلامة - Flag Cleared'), ('chronic_absence', 'غياب مزمن - Chronic Absence Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'في الانتظار - Pending'), ('sent', 'تم الإرسال - Sent'), ('delivered', 'تم التسليم - Delivered'), ('failed', 'فشل - Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_attendance_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord')),
                ('absence_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentabsenceflag')),
            ],
            options={
                'verbose_name': 'Attendance Notification',
                'verbose_name_plural': 'Attendance Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'الإثنين - Lundi'), (2, 'الثلاثاء - Mardi'), (3, 'الأربعاء - Mercredi'), (4, 'الخميس - Jeudi'), (5, 'الجمعة - Vendredi'), (6, 'السبت - Samedi')])),
                ('start_time', models.TimeField(help_text='Session start time (e.g., 08:30)')),
                ('end_time', models.TimeField(help_text='Session end time (e.g., 09:25)')),
                ('session_order', models.PositiveIntegerField(help_text='Period number (1st, 2nd, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Session notes or special instructions')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sessions', to='schools.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='schools.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.schooltimetable')),
            ],
            options={
                'verbose_name': 'Timetable Session',
                'verbose_name_plural': 'Timetable Sessions',
                'ordering': ['day_of_week', 'session_order', 'start_time'],
                'unique_together': {('teacher', 'day_of_week', 'start_time', 'end_time'), ('timetable', 'day_of_week', 'session_order')},
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='attendance.timetablesession'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('student_number', models.CharField(blank=True, help_text='Student number in this class', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='schools.schoolclass')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('student', 'school_class', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'والد - Father'), ('mother', 'والدة - Mother'), ('guardian', 'ولي أمر - Guardian'), ('other', 'أخرى - Other')], default='father', max_length=10)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('notify_absence', models.BooleanField(default=True)),
                ('notify_late', models.BooleanField(default=True)),
                ('notify_flags', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student-Parent Relation',
                'verbose_name_plural': 'Student-Parent Relations',
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('timetable_session', 'date')},
        ),
    ]
