# Generated by Django 5.2.5 on 2025-09-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
