# Generated by Django 5.2.5 on 2026-01-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_delete_studentenrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltimetable',
            unique_together=set(),
        ),
    ]
