# Generated by Django 5.2.5 on 2025-09-10 17:47

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Display name for the media file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the media content')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], help_text='Type of media file', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='The actual file stored in Cloudinary', max_length=255, null=True, verbose_name='file')),
                ('public_id', models.CharField(blank=True, help_text='Cloudinary public ID', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Public URL of the file', max_length=500)),
                ('secure_url', models.URLField(blank=True, help_text='Secure HTTPS URL of the file', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width for images/videos', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height for images/videos', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds for videos/audio', null=True)),
                ('format', models.CharField(blank=True, help_text='File format (jpg, png, pdf, etc.)', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for organization', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility (especially for images)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the file is active and available')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('relation_type', models.CharField(choices=[('ROOM_GALLERY', 'Room Gallery'), ('ROOM_FEATURED', 'Room Featured Image'), ('COURSE_MATERIAL', 'Course Material'), ('COURSE_THUMBNAIL', 'Course Thumbnail'), ('ARTICLE_IMAGE', 'Article Image'), ('ARTICLE_GALLERY', 'Article Gallery'), ('NEWS_BANNER', 'News Banner'), ('NEWS_GALLERY', 'News Gallery'), ('PROFILE_PICTURE', 'Profile Picture'), ('SCHOOL_LOGO', 'School Logo'), ('LESSON_MATERIAL', 'Lesson Material'), ('ASSIGNMENT_ATTACHMENT', 'Assignment Attachment'), ('OTHER', 'Other')], help_text='The type of relationship between the media and the object', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying in galleries (0 = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is the main/featured media for the object')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this specific usage', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('media_file', models.ForeignKey(help_text='The media file in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='media.mediafile')),
            ],
            options={
                'verbose_name': 'Media Relation',
                'verbose_name_plural': 'Media Relations',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type'], name='media_media_media_t_72b3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_media_uploade_dbbf17_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['created_at'], name='media_media_created_74471a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['is_active'], name='media_media_is_acti_8958d6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediarelation',
            index=models.Index(fields=['content_type', 'object_id'], name='media_media_content_004676_idx'),
        ),
        migrations.AddIndex(
            model_name='mediarelation',
            index=models.Index(fields=['relation_type'], name='media_media_relatio_69597b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediarelation',
            index=models.Index(fields=['is_featured'], name='media_media_is_feat_acb61d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediarelation',
            unique_together={('content_type', 'object_id', 'media_file', 'relation_type')},
        ),
    ]
