# Generated by Django 5.2.5 on 2025-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarelation',
            name='relation_type',
            field=models.CharField(choices=[('ROOM_GALLERY', 'Room Gallery'), ('ROOM_FEATURED', 'Room Featured Image'), ('EQUIPMENT_GALLERY', 'Equipment Gallery'), ('EQUIPMENT_FEATURED', 'Equipment Featured Image'), ('VEHICLE_GALLERY', 'Vehicle Gallery'), ('VEHICLE_FEATURED', 'Vehicle Featured Image'), ('VEHICLE_MAINTENANCE_ATTACHMENT', 'Vehicle Maintenance Attachment'), ('VEHICLE_GASOIL_ATTACHMENT', 'Vehicle Fuel Attachment'), ('COURSE_MATERIAL', 'Course Material'), ('COURSE_THUMBNAIL', 'Course Thumbnail'), ('ARTICLE_IMAGE', 'Article Image'), ('ARTICLE_GALLERY', 'Article Gallery'), ('NEWS_BANNER', 'News Banner'), ('NEWS_GALLERY', 'News Gallery'), ('PROFILE_PICTURE', 'Profile Picture'), ('SCHOOL_LOGO', 'School Logo'), ('LESSON_MATERIAL', 'Lesson Material'), ('ASSIGNMENT_ATTACHMENT', 'Assignment Attachment'), ('OTHER', 'Other')], help_text='The type of relationship between the media and the object', max_length=50),
        ),
    ]
