# Generated by Django 5.2.5 on 2025-09-12 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0004_bulkimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_subject',
            field=models.ForeignKey(blank=True, help_text='The subject this teacher specializes in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='schools.subject', verbose_name='School Subject'),
        ),
    ]
