# Generated by Django 5.2.5 on 2025-09-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_school_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
    ]
