# Generated by Django 5.2.5 on 2025-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether user is currently logged in'),
        ),
    ]
