# Generated by Django 5.2.5 on 2025-09-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schoolclass_options_alter_schoolclass_name_and_more'),
        ('users', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teachable_grades',
            field=models.ManyToManyField(blank=True, help_text='The grades this teacher is qualified to teach.', related_name='teachers', to='schools.grade', verbose_name='Teachable Grades'),
        ),
    ]
