# Generated by Django 5.2.5 on 2025-10-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_position_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('ASSISTANT', 'Assistant'), ('IT_SUPPORT', 'IT Support Specialist'), ('ACCOUNTANT', 'Accountant'), ('HR_COORDINATOR', 'HR Coordinator'), ('COUNSELOR', 'Counselor'), ('LIBRARIAN', 'Librarian'), ('NURSE', 'School Nurse'), ('SECURITY', 'Security Officer'), ('MAINTENANCE', 'Maintenance Staff'), ('SUPPORT', 'Support Staff'), ('DRIVER', 'Driver'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Position'),
        ),
    ]
