# Generated by Django 5.2.5 on 2026-01-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount to be applied to the total invoice amount', max_digits=10, verbose_name='Invoice Discount'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='uses_transport',
            field=models.BooleanField(default=False, verbose_name='Uses Transport'),
        ),
    ]
