# Generated by Django 5.2.5 on 2026-01-03 12:36

from django.db import migrations


def set_default_transport(apps, schema_editor):
    StudentEnrollment = apps.get_model('users', 'StudentEnrollment')
    StudentEnrollment.objects.all().update(uses_transport=True)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_studentenrollment_invoice_discount_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_transport),
    ]

