# Generated by Django 5.2.5 on 2026-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_set_default_transport_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director'), ('ASSISTANT', 'Assistant'), ('IT_SUPPORT', 'IT Support Specialist'), ('ACCOUNTANT', 'Accountant'), ('HR_COORDINATOR', 'HR Coordinator'), ('COUNSELOR', 'Counselor'), ('LIBRARIAN', 'Librarian'), ('NURSE', 'School Nurse'), ('SECURITY', 'Security Officer'), ('MAINTENANCE', 'Maintenance Staff'), ('SUPPORT', 'Support Staff'), ('DRIVER', 'Driver'), ('GENERAL_SUPERVISOR', 'General Supervisor'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Position'),
        ),
    ]
