# Generated by Django 5.2.5 on 2025-12-28 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0010_alter_gasoilrecord_id_alter_vehicle_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('languages', 'Languages')], max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lab Tool Category',
                'verbose_name_plural': 'Lab Tool Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(help_text="URL-safe identifier (e.g., 'function-grapher')", max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_ar', models.TextField()),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('instructions_ar', models.TextField(blank=True)),
                ('instructions_fr', models.TextField(blank=True)),
                ('instructions_en', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lab_tools/thumbnails/')),
                ('grade_levels', models.JSONField(default=list, help_text="List of grade codes: ['1AC', '2AC', '3AC', 'TC', '1BAC', '2BAC']")),
                ('features', models.JSONField(default=dict, help_text='Tool-specific features and capabilities')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False, help_text="Show 'NEW' badge")),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('average_duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_tools', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='lab.labtoolcategory')),
            ],
            options={
                'verbose_name': 'Lab Tool',
                'verbose_name_plural': 'Lab Tools',
                'ordering': ['category__order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='LabAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('task_details', models.JSONField(default=dict, help_text="Specific task instructions (e.g., 'Graph these functions')")),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Minutes')),
                ('requires_submission', models.BooleanField(default=True)),
                ('submission_format', models.CharField(choices=[('screenshot', 'Screenshot'), ('file', 'File Upload'), ('text', 'Text Response'), ('automatic', 'Automatic Tracking')], default='screenshot', max_length=50)),
                ('total_points', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('auto_grade', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to='schools.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to='schools.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lab.labtool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('activity_config', models.JSONField(default=dict, help_text='Tool-specific activity configuration')),
                ('grade_levels', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_activities', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lab.labtool')),
            ],
            options={
                'verbose_name': 'Lab Activity',
                'verbose_name_plural': 'Lab Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('interaction_data', models.JSONField(default=dict, help_text='Tool-specific usage data (e.g., functions plotted, calculations performed)')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labactivity')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labassignment')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='lab.labtool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LabAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='lab_assignments/')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='not_started', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lab.labassignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_lab_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignment_submissions', to=settings.AUTH_USER_MODEL)),
                ('usage_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labusage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabToolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('average_duration_seconds', models.PositiveIntegerField(default=0)),
                ('student_users', models.PositiveIntegerField(default=0)),
                ('teacher_users', models.PositiveIntegerField(default=0)),
                ('admin_users', models.PositiveIntegerField(default=0)),
                ('desktop_sessions', models.PositiveIntegerField(default=0)),
                ('tablet_sessions', models.PositiveIntegerField(default=0)),
                ('mobile_sessions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='lab.labtool')),
            ],
            options={
                'verbose_name': 'Lab Tool Analytics',
                'verbose_name_plural': 'Lab Tool Analytics',
                'ordering': ['-date'],
                'unique_together': {('tool', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='labusage',
            index=models.Index(fields=['user', 'tool', '-started_at'], name='lab_labusag_user_id_b25438_idx'),
        ),
        migrations.AddIndex(
            model_name='labusage',
            index=models.Index(fields=['tool', '-started_at'], name='lab_labusag_tool_id_092ebd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labassignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
